---
kind: pipeline
type: kubernetes
name: go-kube

steps:
- name: build and test
  image: golang:1.13-alpine
  commands:
  - go mod download
  - go build
  # - go test
- name: push image
  image: plugins/docker
  settings:
    repo: docker-registry.mlg-dev.local/euiko/go-kube
    registry: docker-registry.mlg-dev.local
    tags: latest